//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class O2S_STUDENTMANAGEMENTEntities : DbContext
    {
        public O2S_STUDENTMANAGEMENTEntities()
            : base("name=O2S_STUDENTMANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_BANGCAP> DM_BANGCAP { get; set; }
        public virtual DbSet<DM_CHUYENNGANH> DM_CHUYENNGANH { get; set; }
        public virtual DbSet<DM_DANTOC> DM_DANTOC { get; set; }
        public virtual DbSet<DM_HUYEN> DM_HUYEN { get; set; }
        public virtual DbSet<DM_NGHENGHIEP> DM_NGHENGHIEP { get; set; }
        public virtual DbSet<DM_QUOCGIA> DM_QUOCGIA { get; set; }
        public virtual DbSet<DM_TINH> DM_TINH { get; set; }
        public virtual DbSet<DM_XA> DM_XA { get; set; }
        public virtual DbSet<SM_KTDAUVAO> SM_KTDAUVAO { get; set; }
        public virtual DbSet<SM_LICENSE> SM_LICENSE { get; set; }
        public virtual DbSet<SM_LICHHOC> SM_LICHHOC { get; set; }
        public virtual DbSet<SM_LOPHOC> SM_LOPHOC { get; set; }
        public virtual DbSet<SM_NGUOITHAN> SM_NGUOITHAN { get; set; }
        public virtual DbSet<SM_OPTION> SM_OPTION { get; set; }
        public virtual DbSet<SM_QTHOCTAP> SM_QTHOCTAP { get; set; }
        public virtual DbSet<SM_STUDENT> SM_STUDENT { get; set; }
        public virtual DbSet<SM_TBLLOG> SM_TBLLOG { get; set; }
        public virtual DbSet<SM_TBLUSER> SM_TBLUSER { get; set; }
        public virtual DbSet<SM_TBLUSER_PERMISSION> SM_TBLUSER_PERMISSION { get; set; }
        public virtual DbSet<SM_VERSION> SM_VERSION { get; set; }
        public virtual DbSet<DM_OTHERLIST> DM_OTHERLIST { get; set; }
        public virtual DbSet<DM_OTHERTYPELIST> DM_OTHERTYPELIST { get; set; }
    }
}
