//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_TBLUSER
    {
        public int id { get; set; }
        public string usercode { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> userstatus { get; set; }
        public Nullable<int> usergnhom { get; set; }
        public string usernote { get; set; }
        public Nullable<int> isremove { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string created_log { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string modified_log { get; set; }
    }
}
