//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_VERSION
    {
        public int id { get; set; }
        public string appversion { get; set; }
        public string app_link { get; set; }
        public Nullable<int> app_type { get; set; }
        public byte[] updateapp { get; set; }
        public Nullable<int> appsize { get; set; }
        public string sqlversion { get; set; }
        public byte[] updatesql { get; set; }
        public Nullable<int> sqlsize { get; set; }
        public Nullable<int> sync_flag { get; set; }
        public Nullable<int> update_flag { get; set; }
        public string urlfullserver { get; set; }
    }
}
