//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_LICHHOC
    {
        public int id { get; set; }
        public string lophoccode { get; set; }
        public string lophocten { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<System.DateTime> ngaydukien { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<decimal> sotiethoc { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> isremove { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string created_log { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string modified_log { get; set; }
    }
}
