//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_LICENSE
    {
        public int id { get; set; }
        public string datakey { get; set; }
        public string licensekey { get; set; }
    }
}
