//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_NGUOITHAN
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> quanhe_id { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<int> nghenghiep_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> xa_id { get; set; }
        public string thonxom { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> isremove { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string created_log { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string modified_log { get; set; }
    }
}
