//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2S_StudentManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_STUDENT
    {
        public int id { get; set; }
        public string studentcode { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public Nullable<int> gioitinh_id { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<int> dantoc_id { get; set; }
        public Nullable<int> nghenghiep_id { get; set; }
        public Nullable<int> tinh_id { get; set; }
        public Nullable<int> huyen_id { get; set; }
        public Nullable<int> xa_id { get; set; }
        public string thonxom { get; set; }
        public string cmtnd { get; set; }
        public Nullable<System.DateTime> cmtnd_ngaycap { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngayvao { get; set; }
        public Nullable<int> trangthai_id { get; set; }
        public Nullable<int> chuyennganh_id { get; set; }
        public Nullable<int> bangcap_id { get; set; }
        public Nullable<int> isremoveid { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string created_log { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string modified_log { get; set; }
    }
}
