<?xml version="1.0" encoding="utf-8"?><Database Name="O2S_QLHV" Class="QuanLyHocVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMIN\SQLEXPRESS;Initial Catalog=O2S_QLHV;Persist Security Info=True;User ID=sa" SettingsObjectName="O2S_QuanLyHocVien.DataAccess.Properties.Settings" SettingsPropertyName="O2S_QLHVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGDIEM" Member="BANGDIEMs">
    <Type Name="BANGDIEM">
      <Column Name="BangDiemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LopHocId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhieuGhiDanhId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemTrungBinh" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="BANGDIEM_BANGDIEMCHITIET" Member="BANGDIEMCHITIETs" ThisKey="BangDiemId" OtherKey="BangDiemId" Type="BANGDIEMCHITIET" />
      <Association Name="HOCVIEN_BANGDIEM" Member="HOCVIEN" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCVIEN" IsForeignKey="true" />
      <Association Name="KHOAHOC_BANGDIEM" Member="KHOAHOC" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="KHOAHOC" IsForeignKey="true" />
      <Association Name="LOPHOC_BANGDIEM" Member="LOPHOC" ThisKey="LopHocId" OtherKey="LopHocId" Type="LOPHOC" IsForeignKey="true" />
      <Association Name="PHIEUGHIDANH_BANGDIEM" Member="PHIEUGHIDANH" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="PHIEUGHIDANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XEPLICHHOC" Member="XEPLICHHOCs">
    <Type Name="XEPLICHHOC">
      <Column Name="XepLichHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LopHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenLopHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PhongHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhongHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianHoc_Full" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CaHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenCaHocFull" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaoVien_ChinhId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenGiaoVien_Chinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TienGiaoVien_Chinh" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GiaoVien_TroGiangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenGiaoVien_TroGiang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TienGiaoVien_TroGiang" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="CAHOC_XEPLICHHOC" Member="CAHOC" ThisKey="CaHocId" OtherKey="CaHocId" Type="CAHOC" IsForeignKey="true" />
      <Association Name="COSOTRUNGTAM_XEPLICHHOC" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="GIANGVIEN_XEPLICHHOC" Member="GIANGVIEN" ThisKey="GiaoVien_ChinhId" OtherKey="GiangVienId" Type="GIANGVIEN" IsForeignKey="true" />
      <Association Name="GIANGVIEN_XEPLICHHOC1" Member="GIANGVIEN1" ThisKey="GiaoVien_TroGiangId" OtherKey="GiangVienId" Type="GIANGVIEN" IsForeignKey="true" />
      <Association Name="LOPHOC_XEPLICHHOC" Member="LOPHOC" ThisKey="LopHocId" OtherKey="LopHocId" Type="LOPHOC" IsForeignKey="true" />
      <Association Name="PHONGHOC_XEPLICHHOC" Member="PHONGHOC" ThisKey="PhongHocId" OtherKey="PhongHocId" Type="PHONGHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BANGDIEMCHITIET" Member="BANGDIEMCHITIETs">
    <Type Name="BANGDIEMCHITIET">
      <Column Name="BangDiemChiTietId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BangDiemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MonHocId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Diem" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BANGDIEM_BANGDIEMCHITIET" Member="BANGDIEM" ThisKey="BangDiemId" OtherKey="BangDiemId" Type="BANGDIEM" IsForeignKey="true" />
      <Association Name="MONHOC_BANGDIEMCHITIET" Member="MONHOC" ThisKey="MonHocId" OtherKey="MonHocId" Type="MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAHOC" Member="CAHOCs">
    <Type Name="CAHOC">
      <Column Name="CaHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCaHoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenCaHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenCaHocFull" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThoiGianTu" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ThoiGianDen" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="CAHOC_XEPLICHHOC" Member="XEPLICHHOCs" ThisKey="CaHocId" OtherKey="CaHocId" Type="XEPLICHHOC" />
      <Association Name="COSOTRUNGTAM_CAHOC" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAUHINHEMAIL" Member="CAUHINHEMAILs">
    <Type Name="CAUHINHEMAIL">
      <Column Name="CauHinhEmailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SMTPServer" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChiEmail" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="XacThucSSL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XacThucTKKhiGui" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCNANG" Member="CHUCNANGs">
    <Type Name="CHUCNANG">
      <Column Name="ChucNangId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChucNang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenChucNang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LoaiChucNangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TabMenuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenForm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="CHUCNANG_PHANQUYENTAIKHOAN" Member="PHANQUYENTAIKHOANs" ThisKey="ChucNangId" OtherKey="ChucNangId" Type="PHANQUYENTAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.COSOTRUNGTAM" Member="COSOTRUNGTAMs">
    <Type Name="COSOTRUNGTAM">
      <Column Name="CoSoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaCoSo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenCoSo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LogoCoSo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="COSOTRUNGTAM_XEPLICHHOC" Member="XEPLICHHOCs" ThisKey="CoSoId" OtherKey="CoSoId" Type="XEPLICHHOC" />
      <Association Name="COSOTRUNGTAM_CAHOC" Member="CAHOCs" ThisKey="CoSoId" OtherKey="CoSoId" Type="CAHOC" />
      <Association Name="COSOTRUNGTAM_GIANGVIEN" Member="GIANGVIENs" ThisKey="CoSoId" OtherKey="CoSoId" Type="GIANGVIEN" />
      <Association Name="COSOTRUNGTAM_HOCVIEN" Member="HOCVIENs" ThisKey="CoSoId" OtherKey="CoSoId" Type="HOCVIEN" />
      <Association Name="COSOTRUNGTAM_KHOAHOC" Member="KHOAHOCs" ThisKey="CoSoId" OtherKey="CoSoId" Type="KHOAHOC" />
      <Association Name="COSOTRUNGTAM_LOPHOC" Member="LOPHOCs" ThisKey="CoSoId" OtherKey="CoSoId" Type="LOPHOC" />
      <Association Name="COSOTRUNGTAM_PHIEUGHIDANH" Member="PHIEUGHIDANHs" ThisKey="CoSoId" OtherKey="CoSoId" Type="PHIEUGHIDANH" />
      <Association Name="COSOTRUNGTAM_PHIEUTHU" Member="PHIEUTHUs" ThisKey="CoSoId" OtherKey="CoSoId" Type="PHIEUTHU" />
      <Association Name="COSOTRUNGTAM_PHONGHOC" Member="PHONGHOCs" ThisKey="CoSoId" OtherKey="CoSoId" Type="PHONGHOC" />
    </Type>
  </Table>
  <Table Name="dbo.GIANGDAY" Member="GIANGDAYs">
    <Type Name="GIANGDAY">
      <Column Name="GiangDayId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LopHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiangVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="GIANGVIEN_GIANGDAY" Member="GIANGVIEN" ThisKey="GiangVienId" OtherKey="GiangVienId" Type="GIANGVIEN" IsForeignKey="true" />
      <Association Name="LOPHOC_GIANGDAY" Member="LOPHOC" ThisKey="LopHocId" OtherKey="LopHocId" Type="LOPHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIANGVIEN" Member="GIANGVIENs">
    <Type Name="GIANGVIEN">
      <Column Name="GiangVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGiangVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenGiangVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NgayBatDauLamViec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="GIANGVIEN_XEPLICHHOC" Member="XEPLICHHOCs" ThisKey="GiangVienId" OtherKey="GiaoVien_ChinhId" Type="XEPLICHHOC" />
      <Association Name="GIANGVIEN_XEPLICHHOC1" Member="XEPLICHHOCs1" ThisKey="GiangVienId" OtherKey="GiaoVien_TroGiangId" Type="XEPLICHHOC" />
      <Association Name="GIANGVIEN_GIANGDAY" Member="GIANGDAYs" ThisKey="GiangVienId" OtherKey="GiangVienId" Type="GIANGDAY" />
      <Association Name="COSOTRUNGTAM_GIANGVIEN" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="TAIKHOAN_GIANGVIEN" Member="TAIKHOAN" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONTHUCHI" Member="HOADONTHUCHIs">
    <Type Name="HOADONTHUCHI">
      <Column Name="HoaDonThuChiId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LoaiChungTuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenNguoiLap" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAICHUNGTU_HOADONTHUCHI" Member="LOAICHUNGTU" ThisKey="LoaiChungTuId" OtherKey="LoaiChungTuId" Type="LOAICHUNGTU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOCPHIHOCVIEN" Member="HOCPHIHOCVIENs">
    <Type Name="HOCPHIHOCVIEN">
      <Column Name="HocPhiHocVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhieuGhiDanhId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DmDichVuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PhieuThuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="HOCVIEN_HOCPHIHOCVIEN" Member="HOCVIEN" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCVIEN" IsForeignKey="true" />
      <Association Name="PHIEUGHIDANH_HOCPHIHOCVIEN" Member="PHIEUGHIDANH" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="PHIEUGHIDANH" IsForeignKey="true" />
      <Association Name="PHIEUTHU_HOCPHIHOCVIEN" Member="PHIEUTHU" ThisKey="PhieuThuId" OtherKey="PhieuThuId" Type="PHIEUTHU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOCVIEN" Member="HOCVIENs">
    <Type Name="HOCVIEN">
      <Column Name="HocVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiHocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHocVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenHocVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NgayTiepNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SdtBo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EmailBo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SdtMe" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="EmailMe" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NguoiTuVanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNguoiTuVan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOCVIEN_BANGDIEM" Member="BANGDIEMs" ThisKey="HocVienId" OtherKey="HocVienId" Type="BANGDIEM" />
      <Association Name="HOCVIEN_HOCPHIHOCVIEN" Member="HOCPHIHOCVIENs" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCPHIHOCVIEN" />
      <Association Name="HOCVIEN_LICHSUTUVAN" Member="LICHSUTUVANs" ThisKey="HocVienId" OtherKey="HocVienId" Type="LICHSUTUVAN" />
      <Association Name="HOCVIEN_PHIEUGHIDANH" Member="PHIEUGHIDANHs" ThisKey="HocVienId" OtherKey="HocVienId" Type="PHIEUGHIDANH" />
      <Association Name="HOCVIEN_PHIEUTHU" Member="PHIEUTHUs" ThisKey="HocVienId" OtherKey="HocVienId" Type="PHIEUTHU" />
      <Association Name="COSOTRUNGTAM_HOCVIEN" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="LOAIHOCVIEN_HOCVIEN" Member="LOAIHOCVIEN" ThisKey="LoaiHocVienId" OtherKey="LoaiHocVienId" Type="LOAIHOCVIEN" IsForeignKey="true" />
      <Association Name="TAIKHOAN_HOCVIEN" Member="TAIKHOAN" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOAHOC" Member="KHOAHOCs">
    <Type Name="KHOAHOC">
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HocPhi" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoTietHoc" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KHOAHOC_BANGDIEM" Member="BANGDIEMs" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="BANGDIEM" />
      <Association Name="KHOAHOC_KHOAHOC_MONHOC" Member="KHOAHOC_MONHOCs" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="KHOAHOC_MONHOC" />
      <Association Name="KHOAHOC_LOPHOC" Member="LOPHOCs" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="LOPHOC" />
      <Association Name="KHOAHOC_PHIEUGHIDANH" Member="PHIEUGHIDANHs" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="PHIEUGHIDANH" />
      <Association Name="COSOTRUNGTAM_KHOAHOC" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOAHOC_MONHOC" Member="KHOAHOC_MONHOCs">
    <Type Name="KHOAHOC_MONHOC">
      <Column Name="KhoaHocMonHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MonHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiemDat" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="KHOAHOC_KHOAHOC_MONHOC" Member="KHOAHOC" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="KHOAHOC" IsForeignKey="true" />
      <Association Name="MONHOC_KHOAHOC_MONHOC" Member="MONHOC" ThisKey="MonHocId" OtherKey="MonHocId" Type="MONHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICENSE" Member="LICENSEs">
    <Type Name="LICENSE">
      <Column Name="LicenseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataKey" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LicenseKey" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHSUTUVAN" Member="LICHSUTUVANs">
    <Type Name="LICHSUTUVAN">
      <Column Name="LichSuTuVanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiTuVan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NoiDungTuVan" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="KetQuaTuVan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NgayTuVan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="HOCVIEN_LICHSUTUVAN" Member="HOCVIEN" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAICHUNGTU" Member="LOAICHUNGTUs">
    <Type Name="LOAICHUNGTU">
      <Column Name="LoaiChungTuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiChungTu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenLoaiChungTu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAICHUNGTU_HOADONTHUCHI" Member="HOADONTHUCHIs" ThisKey="LoaiChungTuId" OtherKey="LoaiChungTuId" Type="HOADONTHUCHI" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHOCVIEN" Member="LOAIHOCVIENs">
    <Type Name="LOAIHOCVIEN">
      <Column Name="LoaiHocVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiHocVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenLoaiHocVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAIHOCVIEN_HOCVIEN" Member="HOCVIENs" ThisKey="LoaiHocVienId" OtherKey="LoaiHocVienId" Type="HOCVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINHANVIEN" Member="LOAINHANVIENs">
    <Type Name="LOAINHANVIEN">
      <Column Name="LoaiNhanVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiNhanVien" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenLoaiNhanVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="NHANVIENs" ThisKey="LoaiNhanVienId" OtherKey="LoaiNhanVienId" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITAIKHOAN" Member="LOAITAIKHOANs">
    <Type Name="LOAITAIKHOAN">
      <Column Name="LoaiTaiKhoanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenLoaiTaiKhoan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAITAIKHOAN_TAIKHOAN" Member="TAIKHOANs" ThisKey="LoaiTaiKhoanId" OtherKey="LoaiTaiKhoanId" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOGEVENT" Member="LOGEVENTs">
    <Type Name="LOGEVENT">
      <Column Name="LogEventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiGianLog" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChucNangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChucNang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenForm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GiaTriCu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GiaTriMoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHocVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenHocVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TenMayTinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPMayTinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CauHinhMayTinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOPHOC" Member="LOPHOCs">
    <Type Name="LOPHOC">
      <Column Name="LopHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLopHoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenLopHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SiSoToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOPHOC_BANGDIEM" Member="BANGDIEMs" ThisKey="LopHocId" OtherKey="LopHocId" Type="BANGDIEM" />
      <Association Name="LOPHOC_XEPLICHHOC" Member="XEPLICHHOCs" ThisKey="LopHocId" OtherKey="LopHocId" Type="XEPLICHHOC" />
      <Association Name="LOPHOC_GIANGDAY" Member="GIANGDAYs" ThisKey="LopHocId" OtherKey="LopHocId" Type="GIANGDAY" />
      <Association Name="COSOTRUNGTAM_LOPHOC" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="KHOAHOC_LOPHOC" Member="KHOAHOC" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="KHOAHOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MONHOC" Member="MONHOCs">
    <Type Name="MONHOC">
      <Column Name="MonHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMonHoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiemToiDa" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="MONHOC_BANGDIEMCHITIET" Member="BANGDIEMCHITIETs" ThisKey="MonHocId" OtherKey="MonHocId" Type="BANGDIEMCHITIET" />
      <Association Name="MONHOC_KHOAHOC_MONHOC" Member="KHOAHOC_MONHOCs" ThisKey="MonHocId" OtherKey="MonHocId" Type="KHOAHOC_MONHOC" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiNhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NgayBatDauLamViec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="LOAINHANVIEN" ThisKey="LoaiNhanVienId" OtherKey="LoaiNhanVienId" Type="LOAINHANVIEN" IsForeignKey="true" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="TAIKHOAN" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYENTAIKHOAN" Member="PHANQUYENTAIKHOANs">
    <Type Name="PHANQUYENTAIKHOAN">
      <Column Name="PhanQuyenTaiKhoanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChucNangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Them" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XuatFile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="CHUCNANG_PHANQUYENTAIKHOAN" Member="CHUCNANG" ThisKey="ChucNangId" OtherKey="ChucNangId" Type="CHUCNANG" IsForeignKey="true" />
      <Association Name="TAIKHOAN_PHANQUYENTAIKHOAN" Member="TAIKHOAN" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUGHIDANH" Member="PHIEUGHIDANHs">
    <Type Name="PHIEUGHIDANH">
      <Column Name="PhieuGhiDanhId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhoaHocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhieuGhiDanh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayGhiDanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DaDong" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="MienGiam_PhanTram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MienGiam_Tien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="LyDoMienGiam" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ConNo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HocPhiKH" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoTietKH" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HocPhiHocVienKH" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SoTietHocVienKH" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThuKhoanKhac" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LyDoXoa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiXoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PHIEUGHIDANH_BANGDIEM" Member="BANGDIEMs" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="BANGDIEM" />
      <Association Name="PHIEUGHIDANH_HOCPHIHOCVIEN" Member="HOCPHIHOCVIENs" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="HOCPHIHOCVIEN" />
      <Association Name="PHIEUGHIDANH_PHIEUTHU" Member="PHIEUTHUs" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="PHIEUTHU" />
      <Association Name="COSOTRUNGTAM_PHIEUGHIDANH" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="HOCVIEN_PHIEUGHIDANH" Member="HOCVIEN" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCVIEN" IsForeignKey="true" />
      <Association Name="KHOAHOC_PHIEUGHIDANH" Member="KHOAHOC" ThisKey="KhoaHocId" OtherKey="KhoaHocId" Type="KHOAHOC" IsForeignKey="true" />
      <Association Name="TAIKHOAN_PHIEUGHIDANH" Member="TAIKHOAN" ThisKey="NhanVienId" OtherKey="TaiKhoanId" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTHU" Member="PHIEUTHUs">
    <Type Name="PHIEUTHU">
      <Column Name="PhieuThuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhieuThu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoThuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuGhiDanhId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HocVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiPhieuThuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianThu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LyDoHuy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiHuy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThoiGianHuy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PHIEUTHU_HOCPHIHOCVIEN" Member="HOCPHIHOCVIENs" ThisKey="PhieuThuId" OtherKey="PhieuThuId" Type="HOCPHIHOCVIEN" />
      <Association Name="COSOTRUNGTAM_PHIEUTHU" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
      <Association Name="HOCVIEN_PHIEUTHU" Member="HOCVIEN" ThisKey="HocVienId" OtherKey="HocVienId" Type="HOCVIEN" IsForeignKey="true" />
      <Association Name="PHIEUGHIDANH_PHIEUTHU" Member="PHIEUGHIDANH" ThisKey="PhieuGhiDanhId" OtherKey="PhieuGhiDanhId" Type="PHIEUGHIDANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGHOC" Member="PHONGHOCs">
    <Type Name="PHONGHOC">
      <Column Name="PhongHocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhongHoc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenPhongHoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PHONGHOC_XEPLICHHOC" Member="XEPLICHHOCs" ThisKey="PhongHocId" OtherKey="PhongHocId" Type="XEPLICHHOC" />
      <Association Name="COSOTRUNGTAM_PHONGHOC" Member="COSOTRUNGTAM" ThisKey="CoSoId" OtherKey="CoSoId" Type="COSOTRUNGTAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TaiKhoanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiTaiKhoanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="TAIKHOAN_GIANGVIEN" Member="GIANGVIENs" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="GIANGVIEN" />
      <Association Name="TAIKHOAN_HOCVIEN" Member="HOCVIENs" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="HOCVIEN" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="NHANVIENs" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="NHANVIEN" />
      <Association Name="TAIKHOAN_PHANQUYENTAIKHOAN" Member="PHANQUYENTAIKHOANs" ThisKey="TaiKhoanId" OtherKey="TaiKhoanId" Type="PHANQUYENTAIKHOAN" />
      <Association Name="TAIKHOAN_PHIEUGHIDANH" Member="PHIEUGHIDANHs" ThisKey="TaiKhoanId" OtherKey="NhanVienId" Type="PHIEUGHIDANH" />
      <Association Name="LOAITAIKHOAN_TAIKHOAN" Member="LOAITAIKHOAN" ThisKey="LoaiTaiKhoanId" OtherKey="LoaiTaiKhoanId" Type="LOAITAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINTRUNGTAM" Member="THONGTINTRUNGTAMs">
    <Type Name="THONGTINTRUNGTAM">
      <Column Name="ThongTinTrungTamId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTrungTam" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TenTrungTam" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VERSION" Member="VERSIONs">
    <Type Name="VERSION">
      <Column Name="VersionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AppLink" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AppType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppResults" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AppMD5Hash" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SqlVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SqlResults" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.QUYDINH" Member="QUYDINHs">
    <Type Name="QUYDINH">
      <Column Name="QuyDinhId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoSoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaQuyDinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenQuyDinh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsRemove" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedLog" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>